### ISSUE TITLE
JWT query param is now case sensitive

### ISSUE THREAD

**Issue by adbs1** [TheCacophonyProject/cacophony-api#117]
The cacophony-web project uses and uppercase JWT query param, the api now requires lowercase as of the following commit:

https://github.com/TheCacophonyProject/cacophony-api/commit/680083ead21f9f76e25663525f2b4e5568b2d687

Fixed by changing to:
 const token = ExtractJwt.fromAuthHeaderWithScheme('JWT')(req);

**Comment by mjs** [comment]
Did you establish if this was an issue with a stale `node_modules` directory?

**Comment by adbs1** [comment]
I believe so, I rolled back my change and resinstalled and it's now working as expected.

**Comment by mjs** [comment]
Ok great.
