### ISSUE TITLE
When a user creates a new group they should be an admin (they are not at the moment)

### ISSUE THREAD

**Issue by clare** [TheCacophonyProject/cacophony-api#148]

**Comment by agronauts** [comment]
@clare I interpreted this to mean "When a user creates a group, they should become the admin of that group". If that's the case, I was unable to reproduce this bug: I could create a group with a new user and use their credentials to add another user to that group. I also found they had admin writes to the group in the database.

Were you instead meaning "A user must be an admin to create a group"?

Furthermore, does the concept of a global admin user exist, independent of groups? All I can see that would distinguish that is the `Users.globalPermission` field set to `write`. @mjs

**Comment by mjs** [comment]
That was my interpretation of this bug too. Do you have any more info @clare? 

I'm on holidays at the moment so can't dig into this too much.

**Comment by clare** [comment]
Yes this is what needs to happen.
