### ISSUE TITLE
Remove data field from PATCH users and instead use standard JSON input

### ISSUE THREAD

**Issue by jackodsteel** [TheCacophonyProject/cacophony-api#199]
Currently the PATCH /api/v1/users endpoint expects a JSON object containing a single "data" field, which contains a string which is supposed to decode to the expected JSON blob.

There's no reason to have this indirection, instead we should take the fields directly in JSON.

Current:
```
{
	"data": "{\"password\": \"a_new_password\", \"username\": \"a_new_username\"}"
}
```

New proposed:
```
{
	"password": "a_new_password",
	"username": "a_new_username"
}
```

As an intermediate period we can still support both while downstream services switch. This would be done by checking if there was a "data" field, if so use the legacy implementation. If not then use the new. Once all services are migrated, remove legacy.

**Comment by mjs** [comment]
This is a nice improvement. :+1: 

cacophony-browse is the only consumer of this API that I'm aware of, so the transition period can be quite small.
