### ISSUE TITLE
Include failed file processing jobs through the API request.

### ISSUE THREAD

**Issue by CameronRP** [TheCacophonyProject/cacophony-api#26]
When a file processing job is requests, if the file-processing fails and doesn't respond the file processing job should be included when doing an API request so it can be processed.
This can be detected by if the file processing start time is over an hour old, as a file should not take more than an hour to be processed.

**Comment by mjs** [comment]
This is probably not a great idea. A job that has failed processing is likely to continue failing without human intervention.
