### ISSUE TITLE
Query result `offset` and `limit` fields are returns as strings

### ISSUE THREAD

**Issue by mjs** [TheCacophonyProject/cacophony-api#276]
For some reason the `offset` and `limit` fields returned by the recordings query API are strings.

**Comment by lxop** [comment]
It returns numbers (not strings) for me: 
![image](https://user-images.githubusercontent.com/7370817/89166416-1e817000-d5ce-11ea-8215-8f964a2023ae.png)

**Comment by gferraro** [comment]
Sorry i fixed that without realising there was a ticket for that
