### ISSUE TITLE
Unclear that it is needed or how to configure server.json & database.json

### ISSUE THREAD

**Issue by agronauts** [TheCacophonyProject/cacophony-api#3]
README says that only config.js needs to be made, however it appears that server.json & database.json are also required. There is minimal documentation on how to do this and I am not confident in what they do.

**Comment by CameronRP** [comment]
Yeah the documentation hasn't been properly updated for this yet. I'll look
into updating this soon.

**Comment by agronauts** [comment]
May I also get pushing rights please? Also, is there an IRC or another channel of communication I'm missing? The Kanban board seems neglected.

**Comment by lightweight** [comment]
Thanks for your interest in this, @agronauts - all legit points. I'll have a chat to the crew and see what we can do!

**Comment by mjs** [comment]
Hi @agronauts!

The best communication channel for the project is the mailing list / forum here: http://groups.nzoss.org.nz/groups/projectcacophony

We appreciate your interest in the project but are a little reluctant to give out push access to people who have no track record of contributions. Could you please try submitting some pull requests first? 

We'll be working on improving documentation and making the experience for potential contributors better in the coming weeks. If you are able to give us a head start in this direction that would be fantastic.

**Comment by mjs** [comment]
This was sorted out some time ago.
