### ISSUE TITLE
Change messages/logs to be formatted consistently

### ISSUE THREAD

**Issue by CameronRP** [TheCacophonyProject/cacophony-api#59]
Let's go with all lower case as is commonly done for Go projects.

**Comment by SimonM2000** [comment]
I started on this, but I want to make sure this is what you want. The [Go guidelines](https://github.com/golang/go/wiki/CodeReviewComments#error-strings) say the reason for their error string guide is that such messages are likely to be used within some other context. Is that the case with API messages? The Go guideline also says it doesn't apply to log messages, which are implicitly line-oriented. Their intent is not to present the user with lower-case, unpunctuated messages but rather to ensure the grammar of the containing message is not compromised by the error message.

One issue with this approach is when the string is not just a single statement, for example, in File.js: _"Failed to delete file. Files can only be deleted by the admins and the person who uploaded the file."_ I could simplify the message, but it seems useful to provide the failure & reason for the failure. I could use a hyphen for such messages: _"Failed to delete file - files can only be deleted ..."_. There are several more examples in middleware.js - the hyphen approach would work OK for all of them.

**Comment by mjs** [comment]
Thinking about ti some more, let's go with sentence case for error messages. That makes it easiest to present errors directly to the user and works around the the multiple sentence case.

So "Something didn't work." (note the trailing full stop) and "Failed to delete file. Files can only be deleted by the admins and the person who uploaded the file." would be compliant messages.

Would you mind confirming that all error messages conform to this style?

**Comment by SimonM2000** [comment]
Sure, will do.
