### ISSUE TITLE
Updates to recording fields aren't limited

### ISSUE THREAD

**Issue by mjs** [TheCacophonyProject/cacophony-api#96]
With with AudioRecordings PUT API the fields that are allowed to be updated are limited. The Recordings PATCH API has no limitations on the fields that may be updated. This is somewhat dangerous.

**Comment by CameronRP** [comment]
This line prevents it. Done a different way to the AudioRecordings.
https://github.com/TheCacophonyProject/cacophony-api/blob/master/models/Recording.js#L172
